### ISSUE TITLE
"loop" fails to loop at end of video

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/app-extension-qmediaplayer#42]
The loop attribute is being written in the html output as 'loop="loop"'

**Comment by hawkeye64** [comment]
This is also an issue with "playsinline" property

**Comment by hawkeye64** [comment]
Fixed in v1.0.2

**Comment by sup3rtrup3r** [comment]
i uninstall last version and get new one, this problem is not fixed when i use loop="loop" or :loop="true". I got this error in console:
![problem](https://user-images.githubusercontent.com/34650897/61179721-180e0800-a609-11e9-8f2f-2c4f8667e61a.png)
My media component looks like this: 
`<q-media-player
			 :autoplay="true"
			 loop="loop"
			 type="video"
			 background-color="black"
			 :no-controls="true"
			 :sources="video.sources"
			 class="video"
		 >
		 </q-media-player>
`

**Comment by hawkeye64** [comment]
Available in v1.0.3 - please let me know how it goes
